### ISSUE TITLE
Function to check whether a given standard exists in STO

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemI40STOLandscape#9]
To develop a method to check whether a given standard exists in STO as an instance. We might think of a python class containing common RDF actions, e.g., inserting a new standard in the KB, updating, deleting an existing standard, etc.

**Comment by mmaltsev** [comment]
Implemented as a [method](https://github.com/i40-Tools/SemI40STOLandscape/blob/2d19279f1b73019c9a9b8f12eefa7908a6def9ed/sto_landscape/STOLandscape.py#L75) in the new class Ontology as a part of STOLandscape module. Via this method existance of any triple can be checked. If predicate and object are not specified - checked triple would be `?sub rdf:type sto:Standard`. Other commonly used methods are implemented as well. Resulting code of enriching the ontology, based on the introduced module can be found [here](https://github.com/i40-Tools/SemI40STOLandscape/blob/master/sto_landscape/sto_enriching.py).
